scss_files:
  - '_scss/**/*.scss'
  - 'assets/**/*.scss'

preprocess_command: "sed '1{/^---$/{:a N;/---$/!ba;d}}'"

linters:
  BorderZero:
    enabled: true
    convention: none
  ChainedClasses:
    enabled: true
  IdSelector:
    enabled: false
  Indentation:
    enabled: true
    character: tab
    width: 1
  LeadingZero:
    enabled: true
    style: include_zero
  PlaceholderInExtend:
    enabled: true
  PropertySortOrder:
    enabled: true
    order: concentric
  PropertyUnits:
    enabled: true
    global: ['px', 'rem', '%']
    properties:
      animation: ['s']
  TrailingZero:
    enabled: true
