# Site settings
title: 'dmzx'
description: null
baseurl: null # the subpath of your site, e.g. /blog/
url: null # the base hostname & protocol for your site


theme: null
plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-sitemap
  - jemoji
excerpt_separator: <!-- more -->
