# Site settings
title: 'dmzx'
description: null
baseurl: null # the subpath of your site, e.g. /blog/
url: null # the base hostname & protocol for your site

# Default settings
defaults:
  -
    scope:
      path: '' # all files
      type: drafts
    values:
      layout: post
      author: dmzx
      permalink: /:title
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      author: dmzx
      permalink: /:title
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: dmzx

# Build settings
theme: null
encoding: 'utf-8'
paginate_path: /page-:num
paginate: 12
timezone: Europe/Amsterdam
exclude:
  - LICENSE
  - Rakefile
  - README.md
  - composer.json
  - composer.lock
  - satis.json
  - Gemfile
  - Gemfile.lock
kramdown:
    input: GFM
    hard_wrap: false
sass:
    sass_dir: _scss
    style: compressed
plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-sitemap
  - jemoji
excerpt_separator: <!-- more -->

verifications:
    google: ''
    yandex: ''

word_per_minute: 180 # WPM
image_view_time: 3   # Seconds

# Needed to build locally
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: dmzx/dmzx.github.io
